# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-29 10:24
from __future__ import unicode_literals

from django.db import migrations
import django_measurement.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=django_measurement.models.MeasurementField(default=0, measurement_class=b'Volume'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='elaboration_time',
            field=django_measurement.models.MeasurementField(default=0, measurement_class=b'Time'),
        ),
    ]
